### ISSUE TITLE
DOI for citing the repo? 

### ISSUE THREAD

**Issue by laurensorensen** [amiaopensource/time-based-media-art#14]
Hi there maintainer(s), I would like to cite this project in academic research, and wondering if you'd be willing to attach a DOI to one of the releases.
There are two services that I've found that can do this, lmk if you need a hand:
http://mozillascience.github.io/code-research-object/
and Zenodo:
https://guides.github.com/activities/citable-code/

Thanks!

**Comment by kfrn** [comment]
OMG! I'm so chuffed by that. 

The Zenodo option looks the more rigorous, with the versioning info. Do you have a preference?

**Comment by laurensorensen** [comment]
:) No preference, whichever you prefer!

**Comment by kfrn** [comment]
DOI added in b1db040f66eff836fe4f7c46d1a5168180c27152 😃
