### ISSUE TITLE
administrative metadata

### ISSUE THREAD

**Issue by ablwr** [amiaopensource/time-based-media-art#19]
Hello, sibling. You might know where this is going... I just added administrative metadata to the open-workflows repository: https://github.com/amiaopensource/open-workflows/pull/68

And perhaps this repo would like to do the same? @kfrn, you are the original creator, how do you feel about also being a maintainer? Also maybe @kgrons, a K-duo!

**Comment by kfrn** [comment]
Yep, I've been maintaining so far, will add myself!

**Comment by retokromer** [comment]
Resolved in https://github.com/amiaopensource/time-based-media-art/commit/afcaa5a8c099c0160813ab4b520ea2939dabe3ee.
