### ISSUE TITLE
make a new release

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/time-based-media-art#26]
I suggest to make a new release, in order to update the DOI entry for this resource.

**Comment by kfrn** [comment]
Cheers @retokromer. I'll comb my bookmarks in the next week or two to see if I have new things to add, and then make a new release. Feel free to prod me on that 😉

**Comment by retokromer** [comment]
@kfrn Do you have time to do it this week? If so, I would use the new release for the training in Hyderabad next week.

**Comment by kfrn** [comment]
I've just made a new release ([link](https://github.com/amiaopensource/time-based-media-art/releases/tag/v2019-12)). Apologies that it wasn't quicker - I've been flat-tack lately!

**Comment by retokromer** [comment]
Thank you, @kfrn! It’s just in time for my teaching in Hyderabad!

**Comment by kfrn** [comment]
Phew! Hope it's useful :)
