### ISSUE TITLE
JSTOR

### ISSUE THREAD

**Issue by retokromer** [amiaopensource/time-based-media-art#36]
The three articles at JSTOR are behind a pay wall and cost USD 49 each.

**Comment by ablwr** [comment]
Should we have someone with university access liberate them and host them somewhere?

**Comment by kfrn** [comment]
I almost certainly have copies saved :smiling_imp: 

Those three are available online. ([example](https://cool.culturalheritage.org/jaic/articles/jaic40-03-004.html)) but it's not very nice formatting to read.

**Comment by retokromer** [comment]
Yep, a kind of HTML version is available for free, but the “nice” text as printed is behind a pay wall.
