### ISSUE TITLE
Local copies of PDFs?

### ISSUE THREAD

**Issue by kfrn** [amiaopensource/time-based-media-art#6]
I remembered that [analog-inspection](https://github.com/amiaopensource/analog-inspection) also has local copies of the PDF resources. Should we do the same here? And are there any copyright concerns?

**Comment by retokromer** [comment]
Good idea! I suggest to add at least all the ones under a CC.

**Comment by kfrn** [comment]
Unfortunately, I don't think that any are declared as such. Hmmm.

**Comment by retokromer** [comment]
If there are no restrictions declared, then… no restrictions are made!

**Comment by kfrn** [comment]
[Done!](https://github.com/amiaopensource/time-based-media-art/commit/e037759744f3602e840c503a45e60d2cb1c0eb44)
And oops, I didn't mean to push to master.

**Comment by retokromer** [comment]
:1st_place_medal:
